### ISSUE TITLE
Could type exports export a <typeuse> instead of <typeidx>?

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/proposal-type-imports#3]
In the proposal, a [type export](https://github.com/WebAssembly/proposal-type-imports/blob/master/proposals/type-imports/Overview.md#exports) must export a type by `<typeidx>`, which means some typedef in the type section.  This rules out exporting `any`, `func`, `i31`, etc, which would be allowed if the `<typeidx>` was replaced with [`<typeuse>`](https://github.com/WebAssembly/gc/blob/master/proposals/gc/MVP.md#type-uses).

The practical use case that suggested this slight generalization is: let's say I want to implement an abstract data type in linear memory.  Ideally, I could do this by exporting `i31` as a type, allowing me to stick the linear memory offset of the data structure directly into the reference value (without having to box it into some GC object).

Another use case is let's say my abstract data type is implemented by an `anyref` (say, any JS value); it'd be more efficient if I didn't have to box that into a `(struct (field anyref))`.

**Comment by rossberg** [comment]
Good point, done. (Recently renamed `<typeuse>` to `<constype>` in the funcref proposal, though admittedly that's still not the most compelling name either.)

**Comment by lukewagner** [comment]
Thanks!
